Network: 
  name: DeepLabv3Plus_r
  num_class: 21  

EMA:
  alpha: 0.99

Optim:
  name: Adam
  lr: 2.5e-3
  weight_decay: 5e-4

Lr_Scheduler:
  name: PolyLR
  step_size: 90
  gamma: 0.1

Dataset: 
  name: pascal
  root_dir: ./data/VOCdevkit/VOC2012
  patch_size: 256
  labeled_num: 125
  batch_size: 4

Labeled_Dataset:
  num_patient: 8
  batch_size: 4

Unlabeled_Dataset:
  batch_size: 4
  aug_mode: cutout

Training_Setting:
  epoch: 200
  device: cuda:0
  save_dir: ./tmp/MT_ReCo_VOC_try
  
Seed: 6895

Reco_Loss:
  is_available: True
  strong_threshold: 0.97
  weak_threshold: 0.7
  temp: 0.5
  num_queries: 128
  num_nagetives: 256